name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_job:
    needs: first_job  # se puede especificar en formato de lista para especificar todos los jobs previos que necesita.
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Segundo Hola Mundo"
