name: "Deploy Código Facilito"

on:
  push:
    branches: ["mains"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      # Los steps son una lista
      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"